### ISSUE TITLE
Graphite backend problem when using same metric-name from multiple client-processes

### ISSUE THREAD

**Issue by RasmusWL** [atlassian/gostatsd#213]
We're encountering an error in the graphite backend. 

Whenever we redeploy a service, the values of our statsd timers go to 0 in graphite for a few minutes. The services changes hosts, and therefore also IP. We run >1 instances of our service, but they all report stats to the same metric name `my_service.my_metric`.

By using tcpdump on the statsd server, we could see the data that gostatsd sends to graphite. We would see something like the following just after a redeploy:

```
stats.timers.my_service.my_metric.time.count 76 1548758589
...
stats.timers.my_service.my_metric.time.count 0 1548758589
...
stats.timers.my_service.my_metric.time.count 0 1548758590
```

So because graphite [only stores the latest value in a given timeslot](https://www.michael-noll.com/blog/2013/11/06/sending-metrics-from-storm-to-graphite/#understanding-how-graphite-handles-incoming-data) graphite will end up only storing 0 :(

So it seems like some thread/goroutine is still expecting to handle `my_service.my_metric` from the old instances that are now dead and therefore keeps on sending zeroes, while a new thread/goroutine is handling the new instaces giving us the real values.

Looking at the metrics in "stable" times with 2 instances of the service running, `stats.timers.my_service.my_metric.time.count` is roughly 50% of what we would expect (also compared to our logs). So it seems like this is in fact a more general problem when we send stats to the same metric name from multiple instances.

---

We're currently using version [`9.0.0`](https://github.com/atlassian/gostatsd/releases/tag/9.0.0). I looked over [the changes since then](https://github.com/atlassian/gostatsd/compare/9.0.0...master) and it didn't look like any of these would have an influence on our problem.

**Comment by tiedotguy** [comment]
This is because tags (and hostname) aren't propagated through to Graphite - see #78.  In Gostatsd it's tracking (roughly):
```
[
{name=my_service.my_metric, hostname=server1, tags=[], value=x},
{name=my_service.my_metric, hostname=server2, tags=[], value=y}
]
```

When this is rendered to Graphite format, Gostatsd doesn't include hostname or tags, resulting in the same metric name written twice at the same timestamp.  When you deploy, you're seeing persistence from the old server (`expiry-interval` option, defaults to `5m`, unfortunately not well documented).  With no new metrics coming in from the old server, Gostatsd will continue to emit 0s until the metric expires.  Due to no tagging, that will conflict with the new server.

One workaround is to set the `ignore-host` option (added in 2.2.0), which would collapse the two metrics above in to:
```
[
{name=my_service.my_metric, hostname="", tags=[], value=x+y},
]
```

It looks like Graphite does [support tags](https://graphite.readthedocs.io/en/latest/tags.html) as of 1.1.x, however I'm not familiar with Graphite generally, so couldn't say how much effort it would be to add proper support.

On a technical level, rendering the tags in to the metric name (`stats.timers.my_service.my_metric.host.server1.time.count`) would be relatively easy, but there is likely "ecosystem" things around Graphite which I'm not aware of (is there a standard for sorting the keys? how to handle valueless tags? should . or : be sanitized? etc)

It's unlikely to be something I'll get to in the short to medium term, however if you want to have a shot at #78, I'd be happy to review / merge the PR.

Random speculation: if this was working before, it's possible that things broke purely because Go uses non-deterministic map enumeration, and it happened to always write the old deployment (value 0) before the new deployment (value 76).  I believe the ordering is consistent within runs, so if you restarted Gostatsd that could change ordering, or if you started emitting new metrics, that could also have changed the ordering due to resizing the map.

**Comment by RasmusWL** [comment]
Thanks for the fast response! we'll try with `ignore-host` :+1: 

I'm not a graphite expert either, but it is my understanding that using `stats.timers.my_service.my_metric.<hostname>.time.count` is not an ideal solution; graphite creates a file for every metric, so by using many dynamic hostnames you can use up all your file descriptors on disk (which actually happened to us when someone used a unique id in the metric path)

**Comment by tiedotguy** [comment]
Thinking through this a bit, how would you feel about an option which disables tags? They would still be parsed, but at the aggregation phase, all tags (and the hostname) would be ignored.  The Graphite backend could do something similar to the New Relic backend, and enable this by default + warn if it's disabled explicitly.

It's not ideal behavior, but it would make it behave "properly" (for some value of properly), and it would be minimal work to add.

**Comment by RasmusWL** [comment]
I think it's an excellent idea to make the graphite backend just work out of the box :heart: 

How about enabling `ignore-host` for the graphite backend by default, and warn if it is disabled explicitly, and until #78 has been fixed, do the same for tags? Then the `ignore-host` won't accidentally be enabled again if #78 is fixed :smile: 

---

Also wanted to let you know that using `--ignore-host` is indeed solving the problem as expected.

**Comment by tiedotguy** [comment]
@RasmusWL, we've got proper tagging support added now, although it doesn't do "node" style.  As a result it's still possible to have conflicts like you had earlier if you're using the earlier styles.  I'm not sure it's worth adding a thing to ignore all tags, but you can raise a separate issue if that's still of interest.
