### ISSUE TITLE
Support forwarder adding custom headers dynamically

### ISSUE THREAD

**Issue by hligit** [atlassian/gostatsd#305]
#261 added support of configuring custom headers to the forwarder. In a multi-tenant environment such as gostatsd deployed as daemonset and shared by multiple pods, we'd like to have support of injecting custom headers from pod metadata.

This could be configured by a pair of flags, similar to the existing `annotation/label-tag-regex` flags of cloud providers.
```
[k8s]
annotation-custom-header-regex = '^gostatsd.atlassian.io/(?P<Service-Name>.*)$'
label-custom-header-regex= ''
```
If matched, forwarder will include the header `Service-Name` with the matched substring in the pod annotation.

Do you think this is a feature fit into gostatsd?

**Comment by tiedotguy** [comment]
As a hypothetical, if there's a single node, with three pods (serviceA, serviceB, and gostatsd-forwarder), where gostatsd-forwarder is configured in a forwarder configuration, pointing to https://gostatsd-upstream

serviceA and serviceB both send to gostatsd-forwarder

Every interval, gostatsd-forwarder makes three requests to https://gostatsd-upstream:
- Intermal metrics (no additional headers, or possibly `x-service-name: gostatsd-forwarder`)
- serviceA metrics (with header `x-service-name: serviceA`)
- serviceB metrics (with header `x-service-name: serviceB`)

Is that a correct understanding of the request?

If so, it seems like there's potential for additional load issues upstream, as there's now twice as much http "stuff" to manage.

If I was to implement it, I'd suggest doing it as a tag->header rewrite, and keep k8s out of it (other than the cloud provider adding the tag), but overall I'm not entirely certain it's a good idea because of the additional volume of requests.

Is this a workaround to help with scaling, due to clustering still not being done?

**Comment by beanliu** [comment]
> If so, it seems like there's potential for additional load issues upstream, as there's now twice as much http "stuff" to manage.

What's the upstream load difference between `single-gostatsd-forwarder-for-all` and `one-gostatsd-forwarder-per-service`?

**Comment by hligit** [comment]
The total number of requests may not be a problem to https://gostatsd-upstream. Since we binpack many services in a single node, number of total `internal-metrics` requests would drop, and total number of serviceN metrics would be similar with before.

**Comment by hligit** [comment]
> If I was to implement it, I'd suggest doing it as a tag->header rewrite, and keep k8s out of it
Good call.

> Is this a workaround to help with scaling, due to clustering still not being done?
Yes

**Comment by tiedotguy** [comment]
@beanliu consider it as:
Old work = http + serviceAmetrics + serviceBmetrics + internalMetrics
New work = (3*http) + serviceAmetrics + serviceBmetrics + internalMetrics + splittingMetrics

There's also some other places for overhead to creep in, such as `compress(serviceA) + compress(serviceB) + compress(internalMetrics)` > `compress(serviceA + serviceB + internalMetrics)`.

That being said - where is the load being applied? If it's an additional 0.5% CPU usage across 100 nodes, that kind of doesn't matter to the forwarder, it's in the noise.  If it's all going to a central upstream server, then that's 100 work units turning in to 300 work units, which is potentially a problem.  But if it's sharded upstream, then that's 100 work units going to 3 different servers (which is why I asked :)

@hligit I don't think binpacking would change the equation, I assume you binpack now, so there can only be a multiplier.  Although since it's to facilitate sharding, then that load gets split out, so it's probably not a concern.

Ideally it would be possible to configure it such that you don't need ...
- serviceA->aggregator 1
- serviceB->aggregator 2
- internal->aggregator 1

... you would only have:
- serviceB -> special aggregator
- serviceA+internal -> default aggregator (in a single request)

I'm very mixed on it, honestly.  It's a lot of infrastructure to work around the actual problem, which is lack of horizontal scaling. But horizontal scaling also doesn't seem to have a lot of forward progress :(

**Comment by beanliu** [comment]
Not sure if I understand that correctly. 
I'll defined the scenarios in details so that we have consensus of what we are talking about.

**Base** case: `one-service-container-with-one-gostatsd-forwarder`: A service container and a gostatsd forwarder are deployed on a node.
**k8sA** case: `multiple-service-container-with-one-gostatsd-forwarder-with-dynamic-http-header-based-on-service-tag`: N service containers and a gostatsd forwarder are deployed on a node, and the gostatsd forwarder would group metrics by service and dispatch data to backend with service header.
**k8sB** case: `multiple-service-container-with-one-gostatsd-forwarder`: N service containers and a gostatsd forwarder are deployed on a node, and the forwarder just dump any batch to backend.

> Old work = http + serviceAmetrics + serviceBmetrics + internalMetrics
New work = (3*http) + serviceAmetrics + serviceBmetrics + internalMetrics + splittingMetrics
@tiedotguy I assume here the "Old work" = k8sB and "New work" = k8sA?

My point is that k8sA is no worse than the base case. The overhead of k8sB may be smaller than k8sA but that just moving workload to backends as we always need sharding.

**Comment by beanliu** [comment]
@tiedotguy FYI, in the above cases, the https://gostatsd-upstream would just be a proxy that dispatch data to different shards of aggregator based on service header.

**Comment by tiedotguy** [comment]
I agrree for k8sA and k8sB, however in Base, does that refer to exactly one service + forwarder per node? (ie, the "micros" model), or does that refer to a service in k8s where the pod includes a gostatsd forwarder, and there may be multiple such pods on a single node?

**Comment by beanliu** [comment]
> does that refer to exactly one service + forwarder per node? (ie, the "micros" model)

yes.

Maybe there's another case: **k8sC** - `multiple-service-container-and-multiple-gostatsd-forwarder-on-a-node`, but that's seems pretty trivial.

**Comment by beanliu** [comment]
We could implement the `dispatch-based-on-metrics-service-tag` logic outside `gostatsd` (middleware always wins), so the question is does it make any sense to include this in `gostatsd`? or is there better solution for k8scompute?

**Comment by hligit** [comment]
@tiedotguy @beanliu It boils down to two cases: dedicated(sidecar) or shared(daemonset). We have gostatsd deployed as sidecars in k8s and are considering moving to daemonset(shared) to reduce the memory footprint. We use quite large EC2 instances and there could be dozens of service pods and gostatsd sidecars on a single node.

I shared the mixed feeling of this too, thus raised issue to gather thoughts here.

**Comment by tiedotguy** [comment]
Ok, gotcha. The difference with Base/k8sC vs k8sA is there's effectively no binpacking in Base, so no need for a dynamic aspect (which if I've kept up to date, is the current situation in Micros)

I agree that k8sA and Base are pretty much the same from the backends perspective.  From the forwarders perspective it's a bit more work (not a lot) because on Base it's 1 service, and on k8sA it's N+1.  As mentioned above though, I don't think it's a big deal for the forwarder tier, it's more the backend, which I know has been problematic.

It could be in or out of gostatsd, or somewhere in between (ie, something consuming gostatsd as a library, since there's a bunch of reusable stuff there).

A couple hypothetical options:
1. add dynamic headers in to the forwarder code, deploy as-is, let your existing infra handle it
2. add url routing to the forwarder code, deploy as a new forwarder tier
3. do 2, but do it in a new binary (ideally in the same repo, but if you need custom logic I can understand it not being open source), consuming gostatsd as a library.

**Comment by tiedotguy** [comment]
@hligit interesting, I didn't realize you were doing that in k8s, I thought it was daemonset already.

I don't have a great answer. Assuming the only problem is scaling, then the **right** solution is clustering.  There's certainly unrelated usages of headers though (such as a dev/prod split), and it will get you where you need to go fastest, and isn't actually that much work (`MetricMap.Split` is a good starting spot)

It feels wrong, but ultimately results are what matters.

**Comment by MovieStoreGuy** [comment]
Then again, clustering has appeared on a backlog :P

**Comment by tiedotguy** [comment]
I mean, if you're trying to motivate me to work on it...
