### ISSUE TITLE
Open to accept DodStatsD types?

### ISSUE THREAD

**Issue by varas** [atlassian/gostatsd#306]
We are wondering if you are open to accept contributions to handle metric types which are particular to DogStatsD like for instance `distribution` https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=go#distribution

**Comment by tiedotguy** [comment]
Absolutely.

I've had vague thoughts about it in the past, and the main concern is how would a non-Datadog backend handle it. Ultimately I think it's fine to drop it, as long as it's expected behavior.

My rough thoughts about it would be:
1. Alias `d` to the Timer type (like Histograms), but add an extra 'magic' tag (such as `gsd_distribution:true`) when a Distribution is parsed.
2. In the aggregator, **if** a configuration option is enabled **and** the tag is present on a timer, then prepare the data as a distribution, otherwise treat it as a regular timer.

This allows for a sender that's not using the dogstatsd client to submit distributions by sending a regular timer/histogram with the magic tag.  It also means that the server has to have it explicitly enabled, so that code path would never occur unless the service owner has knowingly enabled it (which fulfills the "expected behavior" mentioned above).  Possibly a warning could be issued if the flag is enabled and there's a non-Datadog backend.

For the backends:
1. The Datadog backend handles it as expected
2. The stdout backend logs it in a semi-meaningful way.  Since this is usually more for debugging, knowing that the metric is being processed as a distribution is important.
3. The other backends explicitly drop it (maybe issuing a warning on first attempt? not sure)

Does that approach seem sane?

**Comment by tiedotguy** [comment]
If you do want to contribute, it's a good idea to sign the CLA early as well, it's a bit of a manual process on the backend, so it'll save some time later :)

**Comment by varas** [comment]
Yes, dropping/logging at backend level looks good to me.

And sure I'm signing the CLA and will starting contributing.
