### ISSUE TITLE
Counts derived from timers unequal to those derived from histograms

### ISSUE THREAD

**Issue by digitalpoetry** [atlassian/gostatsd#362]
My current understanding of timer metrics and histogram metrics (that is, timer metrics with a gsd_histogram tag) reasons that we should be able to derive the number of data points received per aggregation interval from both forms. For timer metrics, this is given by `timer-metric.count`, and for histogram metrics, this is given by `timer-metric.histogram` filtered by the `le:+Inf` tag.

What is problematic is that I am seeing timer-derived counts are reporting numbers less than histogram-derived counts for some high-throughput regions (prod-east, prod-west, and prod-west2) for the same-scoped timer metric.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/15062913/104140156-17278380-5404-11eb-9a0e-f9171c77fc3a.png">

Whilst they appear to report equal values in low-throughput regions.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/15062913/104140190-43db9b00-5404-11eb-8cb0-d74c8730453b.png">

Despite the indifference, the trend appears to be the same.

@MovieStoreGuy thought you, @tiedotguy, might have some ideas for why we're seeing this difference in the counts derived from these metrics. Do you have any thoughts?

**Comment by tiedotguy** [comment]
The only thing I can think of in the gostatsd pipeline is that histograms use the [absolute number of values](https://github.com/atlassian/gostatsd/blob/master/pkg/statsd/latency_histogram.go#L32), whereas timers [account for sample rate](https://github.com/atlassian/gostatsd/blob/master/pkg/statsd/aggregator.go#L184).

Are either of them being sampled in the busier regions?

**Comment by digitalpoetry** [comment]
Nah, we don't sample our timers 😕

**Comment by tiedotguy** [comment]
My thoughts are:
1. data loss. Shouldn't be on just one metric though.
2. duplicate data. Maybe if there data was processed, but the ack doesn't go through, so the forwarder re-sends it, but again, it should occur everywhere, not on one metric..
3. data alignment (timers are in one window, histograms are in another).  That **might** show up as a shift, but not a gap, because the data is ultimately all there.
4. something on the client.  Other than sampling, I can't think of anything.
5. something on the query.  There's no rollup listed, although I don't know why that would only impact one.  Do you have an aggregation that could be hiding some unexpected extra metric in there?

The data does appear to be rolled up in some form though, 60 seconds per datapoint.  I assume it's still there at different zoom levels?

After ruling out query, I would look at what data is actually going to the backend at various stages of the overall metrics pipeline.

**Comment by digitalpoetry** [comment]
I agree. We don't see much evidence for (1), (2), or (3). Regarding (5), I'm explicitly using sum rollup for both timer and histogram metrics. The gap is still present at different zoom levels.

> After ruling out query, I would look at what data is actually going to the backend at various stages of the overall metrics pipeline.

Looks like we'll need to take this deep-dive from here. Thanks for your input @tiedotguy!
