### ISSUE TITLE
Question: Infinite loop in Receive method?

### ISSUE THREAD

**Issue by msummers-nr** [atlassian/gostatsd#460]
I've been working adding UDS support to the server and don't understand how this section of the [Receive method works](https://github.com/atlassian/gostatsd/blob/cacf8c8a1922473c80a76c6ef8410d053a5335c6/pkg/statsd/receiver.go#L125).

It looks like there is an infinite loop when the client is no longer sending, a new connection is generated when another client connects but the earlier goroutine spins in the for loop.

I only work in Go part-time, my apologies if the answer to this is obvious.

**Comment by tiedotguy** [comment]
Hi

It is an infinite loop, but there's no new connection.  statsd is udp based, so data from all the different clients come in to the one socket (or multiple sockets if you have it enabled).

The detection for closed connection is because when we shutdown, we close the socket (because it's the only way to interrupt the read - there's no context available) - without that checking for a closed connection message, every time we shut down, we spam errors.

I assume UDS means unix domain socket? As I understand it, those are more like TCP than UDP?  If so, you may find https://github.com/atlassian/gostatsd/issues/374#issuecomment-888071184 helpful for the skeleton of how to do that.

**Comment by msummers-nr** [comment]
Ah, got it. Thank you for the response.

Yes, UDS is Unix Domain Socket. UDS is pretty much UDP through a file descriptor with a few other differences. The comment link is helpful.

Thanks again.
