### ISSUE TITLE
runtime.mallocgc takes 30% in profiling

### ISSUE THREAD

**Issue by islue** [atlassian/gostatsd#562]
os: amazon linux 2 x86_64
config:
```
server-mode = "standalone"
backends = "statsdaemon"
expiry-interval = -1
flush-aligned = true
flush-interval = "10s"
ignore-host = true
statser-type = "null"
conn-per-reader = true

[statsdaemon]
address = "another-statsd:8125"
```

profile top:
```
(pprof) top
Showing nodes accounting for 9940ms, 45.98% of 21620ms total
Dropped 255 nodes (cum <= 108.10ms)
Showing top 10 nodes out of 156
      flat  flat%   sum%        cum   cum%
    1910ms  8.83%  8.83%     6700ms 30.99%  runtime.mallocgc
    1640ms  7.59% 16.42%     1870ms  8.65%  runtime.heapBitsSetType
    1330ms  6.15% 22.57%     1640ms  7.59%  syscall.Syscall6
    1210ms  5.60% 28.17%     1210ms  5.60%  runtime.futex
    1030ms  4.76% 32.93%     1970ms  9.11%  runtime.scanobject
     810ms  3.75% 36.68%      810ms  3.75%  runtime.epollwait
     770ms  3.56% 40.24%      770ms  3.56%  runtime.memclrNoHeapPointers
     460ms  2.13% 42.37%      460ms  2.13%  runtime.nextFreeFast (inline)
     400ms  1.85% 44.22%     1820ms  8.42%  runtime.selectgo
     380ms  1.76% 45.98%      490ms  2.27%  golang.org/x/net/internal/socket.(*msghdr).pack
```

Is this normal? gostatsd consumes even more cpu than nodejs' one in my working env.
The traffic is about 50,000 datagrams received per second.

**Comment by tiedotguy** [comment]
Hi,

I'd need to see the full thing to properly assess it (with a memory profile would be even better) - I haven't looked at performance in a long time, and while it does seem a little high, it's definitely possible.

The exact traffic could have a large impact on things as well, the two main things I can think of are:
1. High cardinality traffic
2. If the number of metrics in each packet is low

It's also possible there's something with the statsdaemon backend that I'm not aware of, I've never explicitly worked on that, or used it under load.

I'm not surprised that it consumes more CPU, but I'd be surprised if nodejs is actually processing more traffic.  I think I was able to get gostatsd up to around 100-150kpps back when I worked on it actively.

Ultimately I couldn't get any more out of the single host model, so we switched to a local process model (the forwarding setup), which pushes a lot of work to the local system.  This significantly reduced the load on the central service.

**Comment by islue** [comment]
Hi,

Thank you for your reply.

> 1. High cardinality traffic
> 2. If the number of metrics in each packet is low

Your guess about the use case is exactly right.

> but I'd be surprised if nodejs is actually processing more traffic.

Sorry for the confusion, nodejs cannot handle the whole traffic. There are a lot of receive buffer errors here, which leads to visible data loss.
That's the reason I'm looking for an alternative.

> Ultimately I couldn't get any more out of the single host model, so we switched to a local process model (the forwarding setup)

Well, this is one of the local systems. Perhaps I have to say, we are pushing too much data points to statsd.

I intend to aggregate metrics in a 10s-window locally and forward them to a remote central one.
Neither brubeck nor statsd-c have a statsd backend. It seems that statsdcc has some kind of flushing issue.

I'll try the methods below next
1. Stop to send those not actually used metrics.
2. Find a way in client library to send metrics in some batch mode.

SInce there is not much to do with gostatsd, I'll close the issue.

**Comment by tiedotguy** [comment]
Most client libraries will batch by default, if you're using one that doesn't, that's definitely going to give performance benefits (syscall overhead is non-trivial, and we got a lot of wins by switching to reading a batch of packets per call).

A couple of things you might want to consider:
- sampling - when your throughput is that high (especially from one source), the exact number usually doesn't matter as much, and the shape of the graph is much more important - 99998 or 100003 is basically the same.  Most statsd servers will multiply out the sample rate, so the resultant value is approximately good enough.
- performing local aggregation of counters, specifically do (atomic) increments of variables, and only write out the accumulated value every second or so.  Incrementing a local integer and flushing like this can save massive amounts of resources, because the cost is amortized to basic memory access.  I **think** the datadog statsd client has an option to do this built in, depending on the language you're using.  It doesn't work well with timers though.

If you have the hardware capacity (it sounds like you do), you could try running gostatsd in forwarder mode, and sending the data to another gostatsd server to aggregate.  In forwarder mode, there's some things done differently, which can definitely help (there's no blocking on flush, for instance).  If you do this, you may want to look at reducing the max-parsers (defaults to number of cores), as the total memory usage is a function of core count in this configuration.

Good luck with your project either way!
