### ISSUE TITLE
Metrics are automatically tagged by client hostname

### ISSUE THREAD

**Issue by glennslaven** [atlassian/gostatsd#77]
See [line 315 in aggregator.go](https://github.com/atlassian/gostatsd/blob/master/statsd/aggregator.go#L315)

`tagsKey := formatTagsKey(m.Tags, m.Hostname)`

This results in all incoming metrics being tagged by hostname.  This means that especially for timer metrics the calculations (min, max, median, etc.) are all fragmented by the hostname tag.  When you have a large (and changing depending on load) number of logstash instances sending metrics to gostatsd it means that we can't get the correct numbers out at the end.

I'm wondering if this could be made optional or if there is another way to configure the program to not shard on the tags if not needed.

**Comment by ash2k** [comment]
Yes, and for backends like Datadog it is ok. Also note that this is not just about hostname - cloud provider may add various tags based on source IP address. E.g. AWS availability zone of the source instance, tags on the instance itself.

**Comment by glennslaven** [comment]
@ash2k sure, but for logstash inputs, there's no tags, but I can't stop it from sharding by the client hostname.  If we could have a startup switch that disabled adding the hostname tag it would be great.  

For now I've forked and just replaced `m.Hostname` with an empty string.  This is a terrible hack, but it works and it gets us out of the hole we were in using the node statsd process and it dropping packets.  Because other than that, this program works great!

**Comment by ivan-squixa-com** [comment]
My suggestion would be to make it an optional switch to control appending the incoming hostname to the tag.
If this is "meant to" be a drop in replacement for etsy/statsd, make the default "off". Since that would make it more "compatible". (Of course, changing defaults is a breaking change - ouch)
Otherwise, default "on" to maintain existing operation. (Anyone looking for drop in etsy/statsd will have to be a little more careful)
I think @glennslaven would really like the default to be "off".
I'm sure a PR will be coming from him shortly.

**Comment by tiedotguy** [comment]
@ivan-section-io, @glennslaven, feel free to let me know if this change doesn't behave well enough for your needs.  I may not get to fixing it in the short term if so, but at a new issue (or PR) to refine it can be raised.
